#!/usr/bin/env node
/**
 * Copies `version` from the package manifest into the `PCT_VERSION` constant in the code.
 *
 * The version has to stand in two places at once: the package cannot read its own manifest at
 * runtime, because importing the JSON would drag the whole file into the bundle. So the
 * manifest is the source of truth, this script is the constant's only author (`nx release
 * version` bumps the manifest alone), and `check-package.mjs` point 4 is the gate for the case
 * where somebody bumps the version and skips the script — it reads the **built** artefact.
 *
 * Usage:
 *   node libs/components/stamp-version.mjs           # write
 *   node libs/components/stamp-version.mjs --check   # check only (exit 1 on a mismatch)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(HERE, 'package.json');
const TARGET = join(HERE, 'src/version.ts');

const { version } = JSON.parse(readFileSync(MANIFEST, 'utf8'));
if (!version) {
  console.error('X No `version` field in libs/components/package.json.');
  process.exit(1);
}

const render = (
  v,
) => `// GENERATED by libs/components/stamp-version.mjs — do not edit by hand.
// The source of truth is the \`version\` field in libs/components/package.json; only a copy
// lands here, so that the package can report its version at runtime without pulling the
// manifest into the bundle. A mismatch is blocked by the \`check-package\` gate.

/** The library version — the same one the package manifest carries. */
export const PCT_VERSION = '${v}';
`;

const expected = render(version);
const current = (() => {
  try {
    return readFileSync(TARGET, 'utf8');
  } catch {
    return null;
  }
})();

if (process.argv.includes('--check')) {
  if (current === expected) {
    console.log(`✓ PCT_VERSION matches the manifest (${version}).`);
    process.exit(0);
  }
  console.error(
    `X src/version.ts does not match the manifest (${version}).\n` +
      `  Run: npx nx stamp-version components`,
  );
  process.exit(1);
}

if (current === expected) {
  console.log(`✓ PCT_VERSION already current (${version}) — no change.`);
} else {
  writeFileSync(TARGET, expected);
  console.log(`✓ Wrote PCT_VERSION = ${version} to src/version.ts.`);
}
