// GENERATED by libs/components/stamp-version.mjs — do not edit by hand.
// The source of truth is the `version` field in libs/components/package.json; only a copy
// lands here, so that the package can report its version at runtime without pulling the
// manifest into the bundle. A mismatch is blocked by the `check-package` gate.

/** The library version — the same one the package manifest carries. */
export const PCT_VERSION = '0.1.0';
