// PLIK GENEROWANY — nie edytuj.
// Źródło: docs/00-os.md + docs/wymagania/*.md + docs/lekcje.md
// Generator: node tools/check-docs.mjs --write
//
// Po co: karta sandboxa deklaruje, czego dotyczy przykład. Dopóki było to `string[]`,
// literówka dawała chip prowadzący donikąd — czyli cichą wadę (`wym-os`). Ten sam ruch
// co `PctCssVar` w `lekcja-43`, tylko na drugiej klasie nazw.

/** Identyfikator wymagania z `docs/wymagania/` albo osi z `docs/00-os.md`. */
export type PctReqId =
  | 'wym-a11y-axe'
  | 'wym-a11y-dotyk'
  | 'wym-a11y-kolory-wymuszone'
  | 'wym-a11y-ruch'
  | 'wym-a11y-wbudowana'
  | 'wym-a11y-wcag'
  | 'wym-api-animacje'
  | 'wym-api-atrybuty'
  | 'wym-api-bez-obudowy'
  | 'wym-api-czesci'
  | 'wym-api-czesci-unikalne'
  | 'wym-api-fundament'
  | 'wym-api-generyk'
  | 'wym-api-ikony'
  | 'wym-api-ikony-wlasne'
  | 'wym-api-konfiguracja'
  | 'wym-api-kontener'
  | 'wym-api-liczba'
  | 'wym-api-nakladka'
  | 'wym-api-natywne-pole'
  | 'wym-api-nazwy'
  | 'wym-api-obudowa'
  | 'wym-api-platforma'
  | 'wym-api-ramka'
  | 'wym-api-signal-forms'
  | 'wym-api-sygnaly'
  | 'wym-api-szablony'
  | 'wym-api-teksty'
  | 'wym-api-wielkosc'
  | 'wym-jakosc-e2e'
  | 'wym-jakosc-hydracja'
  | 'wym-jakosc-jednostkowe'
  | 'wym-jakosc-karta'
  | 'wym-jakosc-konsument'
  | 'wym-jakosc-kontrola'
  | 'wym-jakosc-pakiet'
  | 'wym-jakosc-pokrycie'
  | 'wym-jakosc-prefiks'
  | 'wym-jakosc-przegladarki'
  | 'wym-jakosc-rejestr'
  | 'wym-jakosc-scena'
  | 'wym-jakosc-typecheck'
  | 'wym-jakosc-widoki'
  | 'wym-os'
  | 'wym-projekt-angular'
  | 'wym-projekt-aplikacje'
  | 'wym-projekt-core'
  | 'wym-projekt-entrypointy'
  | 'wym-projekt-layout'
  | 'wym-projekt-lib-tokenow'
  | 'wym-projekt-monorepo'
  | 'wym-projekt-najnowsze'
  | 'wym-projekt-pakiet'
  | 'wym-projekt-pliki'
  | 'wym-projekt-prefiks'
  | 'wym-projekt-ssr'
  | 'wym-projekt-tree-shaking'
  | 'wym-projekt-zaleznosci'
  | 'wym-token-artefakty'
  | 'wym-token-bez-opacity'
  | 'wym-token-css'
  | 'wym-token-domkniecie'
  | 'wym-token-dtcg'
  | 'wym-token-dyrektywa'
  | 'wym-token-dystrybucja'
  | 'wym-token-gestosc'
  | 'wym-token-kontrast'
  | 'wym-token-logiczne'
  | 'wym-token-nadpisanie'
  | 'wym-token-nazwy'
  | 'wym-token-pary-tekstu'
  | 'wym-token-poziomy'
  | 'wym-token-referencje'
  | 'wym-token-scoped'
  | 'wym-token-scss'
  | 'wym-token-skorka'
  | 'wym-token-system'
  | 'wym-wydanie-metadane'
  | 'wym-wydanie-ng-add'
  | 'wym-wydanie-semver'
  | 'wym-wydanie-wsparcie';

/** Identyfikator lekcji z `docs/lekcje.md`. Karta może wskazywać dowód, nie tylko obietnicę. */
export type PctLessonId =
  | 'lekcja-1'
  | 'lekcja-2'
  | 'lekcja-3'
  | 'lekcja-4'
  | 'lekcja-5'
  | 'lekcja-6'
  | 'lekcja-7'
  | 'lekcja-8'
  | 'lekcja-9'
  | 'lekcja-10'
  | 'lekcja-11'
  | 'lekcja-12'
  | 'lekcja-13'
  | 'lekcja-14'
  | 'lekcja-15'
  | 'lekcja-16'
  | 'lekcja-17'
  | 'lekcja-18'
  | 'lekcja-19'
  | 'lekcja-20'
  | 'lekcja-21'
  | 'lekcja-22'
  | 'lekcja-23'
  | 'lekcja-24'
  | 'lekcja-25'
  | 'lekcja-26'
  | 'lekcja-27'
  | 'lekcja-28'
  | 'lekcja-29'
  | 'lekcja-30'
  | 'lekcja-31'
  | 'lekcja-32'
  | 'lekcja-33'
  | 'lekcja-34'
  | 'lekcja-35'
  | 'lekcja-36'
  | 'lekcja-37'
  | 'lekcja-38'
  | 'lekcja-39'
  | 'lekcja-40'
  | 'lekcja-41'
  | 'lekcja-42'
  | 'lekcja-43'
  | 'lekcja-44'
  | 'lekcja-45'
  | 'lekcja-46'
  | 'lekcja-47'
  | 'lekcja-48'
  | 'lekcja-49'
  | 'lekcja-50'
  | 'lekcja-51'
  | 'lekcja-52'
  | 'lekcja-53'
  | 'lekcja-54'
  | 'lekcja-55';

/** Cokolwiek, na co karta sandboxa może się powołać. */
export type PctDocId = PctReqId | PctLessonId;
