import {
  booleanAttribute,
  Component,
  computed,
  ElementRef,
  inject,
  input,
  model,
  output,
  signal,
} from '@angular/core';
import type { FormValueControl, ValidationError } from '@angular/forms/signals';
import {
  nextPctId,
  PCT_FIELD,
  pctDescribedBy,
  pctAttachToField,
  pctFieldMessages,
  PctCompareWith,
  PctFieldAppearance,
  PctFieldControl,
  PctLabelStrategy,
  pctSameValue,
} from '@pacit/components/core';

/**
 * A single-choice group. **The group is the form control** (`FormValueControl`), not the
 * individual options — from the form's point of view a radiogroup edits one value
 * (req-api-signal-forms).
 *
 * The options (`pct-radio`) use native `<input type="radio">` elements with a shared `name`
 * attribute, so the browser itself provides arrow navigation and correct Tab behaviour (only
 * the selected option is focusable).
 *
 * The value is of any type `T` (a string by default): the group does not read it from the DOM
 * — the native radio's `value` attribute is a description only, and the choice is reported by
 * `pct-radio`, handing over the value it was given as an input. An option can therefore be a
 * union member or an entity, not just a string.
 *
 * @example
 * <pct-radio-group label="Plan" [formField]="form.plan">
 *   <pct-radio value="free">Free</pct-radio>
 *   <pct-radio value="pro">Pro</pct-radio>
 * </pct-radio-group>
 *
 * @example
 * // `T` comes from the binding; the options have to supply a value of the same type.
 * <pct-radio-group [(value)]="size">
 *   <pct-radio [value]="'sm'">Small</pct-radio>
 * </pct-radio-group>
 */
@Component({
  selector: 'pct-radio-group',
  templateUrl: './radio-group.html',
  styleUrl: './radio-group.scss',
  host: {
    class: 'pct-radio-group',
    role: 'radiogroup',
    '[attr.aria-labelledby]': 'labelledBy()',
    '[attr.aria-describedby]': 'describedBy()',
    '[attr.aria-invalid]': 'showInvalid() ? "true" : null',
    '[attr.aria-required]': 'required() ? "true" : null',
    // `aria-readonly` belongs to the GROUP, not to an option: the `radio` role does not
    // support it (`radiogroup` does), and an attribute disallowed for a role is a critical
    // violation, not a cosmetic one (`lesson-33`).
    '[attr.aria-readonly]': 'readonly() ? "true" : null',
    '[attr.aria-orientation]': 'orientation()',
    '[attr.data-pct-orientation]': 'orientation()',
    '[attr.data-pct-invalid]': 'showInvalid() ? "" : null',
    '[attr.data-pct-disabled]': 'disabled() ? "" : null',
    '[attr.data-pct-in-field]': 'inField ? "" : null',
  },
})
export class PctRadioGroup<T = string>
  implements FormValueControl<T | null>, PctFieldControl
{
  /**
   * The selected value — a required field of the `FormValueControl` contract. `null` means
   * "no option is selected": the state the group is born in and the one a reset returns to.
   */
  readonly value = model<T | null>(null);

  // --- FormUiControl (kept in sync by the FormField directive) ---

  readonly disabled = input(false, { transform: booleanAttribute });
  readonly readonly = input(false, { transform: booleanAttribute });
  readonly invalid = input(false, { transform: booleanAttribute });
  readonly touched = input(false, { transform: booleanAttribute });
  readonly required = input(false, { transform: booleanAttribute });
  readonly errors = input<readonly ValidationError.WithOptionalFieldTree[]>([]);

  /** The shared `name` attribute of the native radios; generated by default. */
  readonly name = input<string>('');

  readonly touch = output<void>();

  // --- component API ---

  readonly label = input<string>('');
  readonly hint = input<string>('');
  readonly orientation = input<'vertical' | 'horizontal'>('vertical');

  /** Value equality — as in `pct-select`; entities are compared by key. */
  readonly compareWith = input<PctCompareWith<T>>(pctSameValue);

  /** The "no choice" value, set when the form is reset. */
  readonly emptyValue = input<T | null>(null);

  /** The options are content projected from outside, so the host DOM is what gets queried —
      a `viewChildren` query does not see the templates of child components, and
      `contentChildren(PctRadio)` would create a circular import. */
  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);

  private controls(): HTMLInputElement[] {
    return Array.from(
      this.hostRef.nativeElement.querySelectorAll<HTMLInputElement>(
        'input[type="radio"]',
      ),
    );
  }

  // --- a11y ---

  private readonly uid = nextPctId('pct-radio-group');
  protected readonly labelId = `${this.uid}-label`;
  protected readonly hintId = `${this.uid}-hint`;
  protected readonly errorId = `${this.uid}-error`;

  /** The name that groups the native radios — without it the browser makes no group. */
  readonly groupName = computed(() => this.name() || this.uid);

  // --- working with the chrome (req-api-no-wrapper) ---

  private readonly fieldApi = inject(PCT_FIELD, { optional: true });
  protected readonly inField = this.fieldApi !== null;

  /** A group is named through `aria-labelledby`, not `<label for>`. */
  readonly controlId = this.uid;
  readonly labelStrategy: PctLabelStrategy = 'labelledby';
  readonly fieldAppearance: PctFieldAppearance = 'bare';

  private readonly fieldDescribedBy = signal<string | null>(null);
  private readonly fieldLabelledBy = signal<string | null>(null);

  setDescribedBy(ids: string | null): void {
    this.fieldDescribedBy.set(ids);
  }

  setLabelledBy(id: string | null): void {
    this.fieldLabelledBy.set(id);
  }

  /** The group's name: the chrome's label, or its own. */
  protected readonly labelledBy = computed(() =>
    this.inField ? this.fieldLabelledBy() : this.label() ? this.labelId : null,
  );

  private readonly messages = pctFieldMessages({
    invalid: this.invalid,
    touched: this.touched,
    errors: this.errors,
  });
  protected readonly errorText = this.messages.errorText;
  readonly showInvalid = this.messages.showInvalid;

  protected readonly showError = computed(
    () => !this.inField && this.messages.showError(),
  );

  protected readonly describedBy = computed(() =>
    this.inField
      ? this.fieldDescribedBy()
      : pctDescribedBy([
          [this.hintId, this.hint() !== ''],
          [this.errorId, this.messages.showError()],
        ]),
  );

  constructor() {
    pctAttachToField(this.fieldApi, this);
  }

  /**
   * Whether a given option is selected (used by `pct-radio`). The absence of a choice is
   * filtered out before the comparison — the application's comparator only ever receives the
   * values it was written for.
   */
  isSelected(optionValue: T): boolean {
    const current = this.value();
    if (current === null || current === undefined) return false;
    return this.compareWith()(current, optionValue);
  }

  /** Selects an option; ignored in readonly mode. */
  select(optionValue: T): void {
    if (this.readonly()) return;
    this.value.set(optionValue);
  }

  markTouched(): void {
    this.touch.emit();
  }

  /** Called by signal forms — focuses the selected option, or the first one. */
  focus(options?: FocusOptions): void {
    const controls = this.controls();
    const target = controls.find((c) => c.checked) ?? controls[0];
    target?.focus(options);
  }

  /** Called by signal forms when the form is reset. */
  reset(): void {
    this.value.set(this.emptyValue());
  }
}
